"use client";

import { useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import { cn } from "@/lib/utils";

/* ------------------------------------------------------------------ */
/*  Data                                                               */
/* ------------------------------------------------------------------ */

interface AccordionItem {
    id: string;
    title: string;
    displayTitle: string; // large stylised text shown on active card
    image: string;
    statHead: string;
    statSub: string;
    link: string;
}

const ACCORDION_ITEMS: AccordionItem[] = [
    {
        id: "food",
        title: "Food & Beverage",
        displayTitle: "Food &\nBeverage",
        image:
            "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=85&fit=crop",
        statHead: "$28 billion+",
        statSub: "processed by F&B stores using RR POS",
        link: "/service",
    },
    {
        id: "retail",
        title: "Retail",
        displayTitle: "Retail",
        image:
            "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&q=85&fit=crop",
        statHead: "$39 billion+",
        statSub: "generated by retailers using RR POS annually",
        link: "/solutions#retail",
    },
    {
        id: "beauty",
        title: "Beauty",
        displayTitle: "Beauty",
        image:
            "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1200&q=85&fit=crop",
        statHead: "$12 billion+",
        statSub: "appointments booked through RR POS every month",
        link: "/service",
    },
    {
        id: "supermarket",
        title: "Super Market",
        displayTitle: "Super\nMarket",
        image:
            "https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200&q=85&fit=crop",
        statHead: "Faster checkout",
        statSub: "barcode-first billing and real-time stock for high-volume aisles",
        link: "/service",
    },
    {
        id: "parking",
        title: "Parking",
        displayTitle: "Parking",
        image:
            "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=1200&q=85&fit=crop",
        statHead: "Quick tickets",
        statSub: "simple fee rules and instant receipts for smooth entry/exit",
        link: "/service",
    },
    {
        id: "fmcg",
        title: "FMCG",
        displayTitle: "FMCG",
        image:
            "https://images.unsplash.com/photo-1580915411954-282cb1b0d780?w=1200&q=85&fit=crop",
        statHead: "Tight control",
        statSub: "batch pricing, fast replenishment, and multi-location visibility",
        link: "/service",
    },
    {
        id: "temples",
        title: "Temples",
        displayTitle: "Temples",
        image:
            "https://commons.wikimedia.org/wiki/Special:FilePath/0081323_Arasuri_Ambaji_mandir,_Shakti_Peeth,_north_Gujarat_037.jpg",
        statHead: "Donation-ready",
        statSub: "simple counters, receipts, and reporting for daily collections",
        link: "/service",
    },
];

/* ------------------------------------------------------------------ */
/*  Small centered title (Visible on INACTIVE cards)                   */
/* ------------------------------------------------------------------ */

function SmallCardTitle({
    text,
    isActive,
    isAnyActive,
}: {
    text: string;
    isActive: boolean;
    isAnyActive: boolean;
}) {
    return (
        <motion.div
            className={cn(
                "absolute inset-0 flex items-center justify-center pointer-events-none z-10 px-4 transition-opacity duration-500",
                isActive ? "opacity-0" : "opacity-100"
            )}
        >
            <span
                className={cn(
                    "text-white font-sans font-medium tracking-tight text-center leading-tight transition-all duration-500",
                    isAnyActive && !isActive
                        ? "text-base md:text-lg"
                        : "text-lg md:text-xl lg:text-2xl"
                )}
            >
                {text}
            </span>
        </motion.div>
    );
}

/* ------------------------------------------------------------------ */
/*  Big stylised display title (Visible on ACTIVE card)                */
/* ------------------------------------------------------------------ */

function BigDisplayTitle({
    text,
    isActive,
}: {
    text: string;
    isActive: boolean;
}) {
    return (
        <AnimatePresence>
            {isActive && (
                <motion.div
                    className="absolute inset-0 flex items-start justify-center pointer-events-none z-10 px-4 pt-[8%]"
                    initial={{ opacity: 0, scale: 0.85, y: 20 }}
                    animate={{ opacity: 1, scale: 1, y: 0 }}
                    exit={{ opacity: 0, scale: 0.9, y: -10 }}
                    transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1] }}
                >
                    <span
                        className="text-white text-center leading-[0.9] whitespace-pre-line select-none"
                        style={{
                            fontFamily: "'Playfair Display', serif",
                            fontWeight: 900,
                            fontStyle: "italic",
                            fontSize: "clamp(2.5rem, 5vw, 4rem)",
                            textShadow: "0 4px 40px rgba(0,0,0,0.5)",
                            letterSpacing: "-0.02em",
                        }}
                    >
                        {text}
                    </span>
                </motion.div>
            )}
        </AnimatePresence>
    );
}

/* ------------------------------------------------------------------ */
/*  Single accordion card                                              */
/* ------------------------------------------------------------------ */

function AccordionCard({
    item,
    isActive,
    isDimmed,
    isAnyActive,
    onMouseEnter,
}: {
    item: AccordionItem;
    isActive: boolean;
    isDimmed: boolean;
    isAnyActive: boolean;
    onMouseEnter: () => void;
}) {
    return (
        <motion.div
            className="relative overflow-hidden rounded-xl cursor-pointer will-change-[flex] min-w-0"
            onMouseEnter={onMouseEnter}
            animate={{
                flex: isActive ? 5 : isDimmed ? 0.8 : 1.8,
            }}
            transition={{
                type: "spring",
                stiffness: 120,
                damping: 24,
                mass: 0.9,
            }}
            style={{ height: "100%" }}
        >
            {/* Background image */}
            <Image
                src={item.image}
                alt={item.title}
                fill
                className={cn(
                    "object-cover transition-transform duration-[1200ms] ease-out",
                    isActive ? "scale-[1.08]" : "scale-100"
                )}
                sizes="(max-width: 640px) 100vw, 40vw"
                unoptimized
            />

            {/* Gradient overlays */}
            <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/20 to-black/10 pointer-events-none" />

            {/* Extra dim for inactive cards */}
            <div
                className={cn(
                    "absolute inset-0 bg-black/60 transition-opacity duration-500 pointer-events-none",
                    isDimmed ? "opacity-100" : "opacity-0"
                )}
            />

            {/* Centered titles - NO cursor tracking */}
            <SmallCardTitle
                text={item.title}
                isActive={isActive}
                isAnyActive={isAnyActive}
            />

            {/* Big display title */}
            <BigDisplayTitle
                text={item.displayTitle}
                isActive={isActive}
            />

            {/* Bottom statistics + learn more - NO cursor tracking */}
            <motion.div
                className={cn(
                    "absolute inset-x-0 bottom-0 z-20 transition-opacity duration-500 ease-out",
                    isActive
                        ? "opacity-100 translate-y-0"
                        : "opacity-0 translate-y-6 pointer-events-none"
                )}
            >
                {/* Divider line */}
                <div className="mx-5 md:mx-7 h-px bg-white/25 overflow-hidden relative">
                    <motion.div
                        className="absolute inset-0 bg-white origin-left"
                        animate={{ scaleX: isActive ? 1 : 0 }}
                        transition={{ duration: 0.6, delay: 0.15 }}
                    />
                </div>

                {/* Stat content */}
                <div className="px-5 md:px-7 pt-4 pb-5 md:pb-7 flex items-end justify-between gap-4">
                    <div>
                        <p
                            className="text-white leading-none mb-1.5"
                            style={{
                                fontFamily: "'Playfair Display', serif",
                                fontWeight: 700,
                                fontSize: "clamp(1.5rem, 2.5vw, 2rem)",
                                letterSpacing: "-0.01em",
                            }}
                        >
                            {item.statHead}
                        </p>
                        <p className="text-white/65 text-sm md:text-[15px] leading-snug max-w-[260px] font-sans">
                            {item.statSub}
                        </p>
                    </div>
                    <Link
                        href={item.link}
                        className="text-white text-sm font-medium border-b border-white/80 pb-0.5 hover:border-white/40 transition-colors whitespace-nowrap font-sans italic"
                    >
                        Learn more
                    </Link>
                </div>
            </motion.div>
        </motion.div>
    );
}

/* ------------------------------------------------------------------ */
/*  Main section                                                       */
/* ------------------------------------------------------------------ */

export default function IndustryAccordion() {
    const [activeId, setActiveId] = useState<string | null>("retail");

    return (
        <section className="bg-white w-full py-16 lg:py-24">
            <div className="mx-auto w-full max-w-screen-xl px-5 md:px-10 lg:px-14">
                {/* Header */}
                <div className="mb-10 lg:mb-14 text-center">
                    <p
                        className="text-xs font-semibold tracking-[0.2em] uppercase mb-4 text-gray-400"
                    >
                        Built for every industry
                    </p>
                    <h2
                        className="text-gray-900 font-semibold leading-[1.15]"
                        style={{
                            fontFamily: "'Playfair Display', serif",
                            fontSize: "clamp(1.75rem, 3.5vw, 2rem)",
                            letterSpacing: "-0.015em",
                        }}
                    >
                        Keep your business growing
                    </h2>
                </div>

                {/* Accordion cards row */}
                <div
                    className="hidden sm:flex gap-2 w-full"
                    style={{ height: "clamp(320px, 46vh, 520px)" }}
                    onMouseLeave={() => setActiveId(null)}
                >
                    {ACCORDION_ITEMS.map((item) => {
                        const isActive = activeId === item.id;
                        const isAnyActive = activeId !== null;
                        const isDimmed = isAnyActive && !isActive;
                        return (
                            <AccordionCard
                                key={item.id}
                                item={item}
                                isActive={isActive}
                                isDimmed={isDimmed}
                                isAnyActive={isAnyActive}
                                onMouseEnter={() => setActiveId(item.id)}
                            />
                        );
                    })}
                </div>

                {/* Mobile stacked layout */}
                <div className="flex flex-col gap-3 sm:hidden">
                    {ACCORDION_ITEMS.map((item) => (
                        <MobileCard key={item.id} item={item} />
                    ))}
                </div>
            </div>
        </section>
    );
}

/* ------------------------------------------------------------------ */
/*  Mobile card (stacked, always shows stats)                          */
/* ------------------------------------------------------------------ */

function MobileCard({ item }: { item: AccordionItem }) {
    return (
        <div className="relative overflow-hidden rounded-xl" style={{ height: 220 }}>
            <Image
                src={item.image}
                alt={item.title}
                fill
                className="object-cover"
                sizes="100vw"
                unoptimized
            />
            <div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/30 to-transparent" />

            {/* Title */}
            <div className="absolute inset-0 flex items-center justify-center z-10">
                <span
                    className="text-white text-center leading-[0.9] select-none"
                    style={{
                        fontFamily: "'Playfair Display', serif",
                        fontWeight: 900,
                        fontStyle: "italic",
                        fontSize: "2.5rem",
                        textShadow: "0 4px 30px rgba(0,0,0,0.5)",
                    }}
                >
                    {item.displayTitle}
                </span>
            </div>

            {/* Bottom stats */}
            <div className="absolute inset-x-0 bottom-0 z-20 px-4 pb-4">
                <div className="h-px bg-white/25 mb-3" />
                <div className="flex items-end justify-between gap-3">
                    <div>
                        <p
                            className="text-white leading-none mb-1"
                            style={{
                                fontFamily: "'Playfair Display', serif",
                                fontWeight: 700,
                                fontSize: "1.5rem",
                            }}
                        >
                            {item.statHead}
                        </p>
                        <p className="text-white/65 text-xs leading-snug max-w-[200px]">
                            {item.statSub}
                        </p>
                    </div>
                    <Link
                        href={item.link}
                        className="text-white text-xs font-medium border-b border-white/80 pb-0.5 italic whitespace-nowrap"
                    >
                        Learn more
                    </Link>
                </div>
            </div>
        </div>
    );
}
