"use client";

import { useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import { cn } from "@/lib/utils";
import { ArrowRight } from "lucide-react";

/* ------------------------------------------------------------------ */
/*  Data                                                               */
/* ------------------------------------------------------------------ */

interface AccordionItem {
    id: string;
    title: string;
    displayTitle: string; // large stylised text shown on active card
    image: string;
    statHead: string;
    statSub: string;
    link: string;
}

const ACCORDION_ITEMS: AccordionItem[] = [
    {
        id: "food",
        title: "Food & Beverage",
        displayTitle: "Food &\nBeverage",
        image:
            "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=85&fit=crop",
        statHead: "$28 billion+",
        statSub: "processed by F&B stores using RR POS",
        link: "/service#food",
    },
    {
        id: "retail",
        title: "Retail",
        displayTitle: "Retail",
        image:
            "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=1200&q=85&fit=crop",
        statHead: "$39 billion+",
        statSub: "generated by retailers using RR POS annually",
        link: "/service#retail",
    },
    {
        id: "beauty",
        title: "Beauty",
        displayTitle: "Beauty",
        image:
            "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1200&q=85&fit=crop",
        statHead: "$12 billion+",
        statSub: "appointments booked through RR POS every month",
        link: "/service#beauty",
    },
    {
        id: "supermarket",
        title: "Super Market",
        displayTitle: "Super\nMarket",
        image:
            "https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200&q=85&fit=crop",
        statHead: "Faster checkout",
        statSub: "barcode-first billing and real-time stock for high-volume aisles",
        link: "/service#supermarket",
    },
    {
        id: "parking",
        title: "Parking",
        displayTitle: "Parking",
        image:
            "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=1200&q=85&fit=crop",
        statHead: "Quick tickets",
        statSub: "simple fee rules and instant receipts for smooth entry/exit",
        link: "/service#parking",
    },
    {
        id: "fmcg",
        title: "FMCG",
        displayTitle: "FMCG",
        image:
            "https://images.unsplash.com/photo-1580915411954-282cb1b0d780?w=1200&q=85&fit=crop",
        statHead: "Tight control",
        statSub: "batch pricing, fast replenishment, and multi-location visibility",
        link: "/service#fmcg",
    },
    {
        id: "temples",
        title: "Temples",
        displayTitle: "Temples",
        image: "/services/temples.jpg",
        statHead: "Donation-ready",
        statSub: "simple counters, receipts, and reporting for daily collections",
        link: "/service#temples",
    }
];

/* ------------------------------------------------------------------ */
/*  Small centered title (Visible on INACTIVE cards)                   */
/* ------------------------------------------------------------------ */

function SmallCardTitle({
    text,
    isActive,
    isAnyActive,
}: {
    text: string;
    isActive: boolean;
    isAnyActive: boolean;
}) {
    return (
        <motion.div
            className={cn(
                "absolute inset-0 flex items-center justify-center pointer-events-none z-10 px-4 transition-opacity duration-500",
                isActive ? "opacity-0" : "opacity-100"
            )}
        >
            <span
                className={cn(
                    "text-white font-sans font-medium tracking-tight text-center leading-tight transition-all duration-500",
                    isAnyActive && !isActive
                        ? "text-base md:text-lg"
                        : "text-lg md:text-xl lg:text-2xl"
                )}
            >
                {text}
            </span>
        </motion.div>
    );
}

/* ------------------------------------------------------------------ */
/*  Big stylised display title (Visible on ACTIVE card)                */
/* ------------------------------------------------------------------ */

function BigDisplayTitle({
    text,
    isActive,
}: {
    text: string;
    isActive: boolean;
}) {
    return (
        <AnimatePresence>
            {isActive && (
                <motion.div
                    className="absolute inset-0 flex items-start justify-center pointer-events-none z-10 px-4 pt-[8%]"
                    initial={{ opacity: 0, scale: 0.85, y: 20 }}
                    animate={{ opacity: 1, scale: 1, y: 0 }}
                    exit={{ opacity: 0, scale: 0.9, y: -10 }}
                    transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1] }}
                >
                    <span
                        className="font-serif font-bold tracking-tight text-white text-center leading-[0.9] whitespace-pre-line select-none"
                        style={{
                            fontSize: "clamp(2.5rem, 5vw, 4rem)",
                            textShadow: "0 4px 40px rgba(0,0,0,0.5)",
                        }}
                    >
                        {text}
                    </span>
                </motion.div>
            )}
        </AnimatePresence>
    );
}

/* ------------------------------------------------------------------ */
/*  Single accordion card                                              */
/* ------------------------------------------------------------------ */

function AccordionCard({
    item,
    isActive,
    isDimmed,
    isAnyActive,
    onMouseEnter,
}: {
    item: AccordionItem;
    isActive: boolean;
    isDimmed: boolean;
    isAnyActive: boolean;
    onMouseEnter: () => void;
}) {
    return (
        <motion.div
            className="relative overflow-hidden rounded-xl cursor-pointer will-change-[flex] min-w-0"
            onMouseEnter={onMouseEnter}
            animate={{
                flex: isActive ? 5 : isDimmed ? 0.8 : 1.8,
            }}
            transition={{
                type: "spring",
                stiffness: 120,
                damping: 24,
                mass: 0.9,
            }}
            style={{ height: "100%" }}
        >
            {/* Background image */}
            <Image
                src={item.image}
                alt={item.title}
                fill
                className={cn(
                    "object-cover transition-transform duration-[1200ms] ease-out",
                    item.id === "temples" && "object-[center_25%]",
                    isActive ? "scale-[1.08]" : "scale-100"
                )}
                sizes="(max-width: 640px) 100vw, 40vw"
                priority={item.id === "retail"}
                unoptimized={item.image.includes("wikimedia.org")}
            />

            {/* Gradient overlays */}
            <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/20 to-black/10 pointer-events-none" />

            {/* Extra dim for inactive cards */}
            <div
                className={cn(
                    "absolute inset-0 bg-black/60 transition-opacity duration-500 pointer-events-none",
                    isDimmed ? "opacity-100" : "opacity-0"
                )}
            />

            {/* Centered titles - NO cursor tracking */}
            <SmallCardTitle
                text={item.title}
                isActive={isActive}
                isAnyActive={isAnyActive}
            />

            {/* Big display title */}
            <BigDisplayTitle
                text={item.displayTitle}
                isActive={isActive}
            />

            {/* Bottom statistics + learn more - NO cursor tracking */}
            <motion.div
                className={cn(
                    "absolute inset-x-0 bottom-0 z-20 transition-opacity duration-500 ease-out",
                    isActive
                        ? "opacity-100 translate-y-0"
                        : "opacity-0 translate-y-6 pointer-events-none"
                )}
            >
                {/* Divider line */}
                <div className="mx-5 md:mx-7 h-px bg-white/25 overflow-hidden relative">
                    <motion.div
                        className="absolute inset-0 bg-white origin-left"
                        animate={{ scaleX: isActive ? 1 : 0 }}
                        transition={{ duration: 0.6, delay: 0.15 }}
                    />
                </div>

                {/* Stat content */}
                <div className="px-5 md:px-7 pt-4 pb-5 md:pb-7 flex items-end justify-between gap-4">
                    <div>
                        <p
                            className="text-white font-sans font-bold tracking-tight leading-none mb-1.5"
                            style={{
                                fontSize: "clamp(1.5rem, 2.5vw, 2rem)",
                            }}
                        >
                            {item.statHead}
                        </p>
                        <p className="text-white/65 text-sm md:text-[15px] leading-snug max-w-[260px] font-sans">
                            {item.statSub}
                        </p>
                    </div>
                    <Link
                        href={item.link}
                        className="text-white text-sm font-medium border-b border-white/80 pb-0.5 hover:border-white/40 transition-colors whitespace-nowrap font-sans italic"
                    >
                        Learn more
                    </Link>
                </div>
            </motion.div>
        </motion.div>
    );
}

/* ------------------------------------------------------------------ */
/*  Main section                                                       */
/* ------------------------------------------------------------------ */

export default function IndustryAccordion() {
    const [activeId, setActiveId] = useState<string | null>("retail");

    return (
        <section className="bg-white w-full py-16 lg:py-24">
            <div className="mx-auto w-full max-w-screen-xl px-5 md:px-10 lg:px-14">
                {/* Header */}
                <div className="mb-10 lg:mb-14 text-center">
                    <p
                        className="text-xs font-semibold tracking-[0.2em] uppercase mb-4 text-gray-400"
                    >
                        Built for every industry
                    </p>
                    <h2
                        className="text-gray-900 font-serif font-semibold leading-[1.15] tracking-tight"
                        style={{
                            fontSize: "clamp(1.75rem, 3.5vw, 2rem)",
                        }}
                    >
                        Keep your business growing
                    </h2>
                </div>

                {/* Accordion cards row */}
                <div
                    className="hidden sm:flex gap-2 w-full"
                    style={{ height: "clamp(320px, 46vh, 520px)" }}
                    onMouseLeave={() => setActiveId(null)}
                >
                    {ACCORDION_ITEMS.map((item) => {
                        const isActive = activeId === item.id;
                        const isAnyActive = activeId !== null;
                        const isDimmed = isAnyActive && !isActive;
                        return (
                            <AccordionCard
                                key={item.id}
                                item={item}
                                isActive={isActive}
                                isDimmed={isDimmed}
                                isAnyActive={isAnyActive}
                                onMouseEnter={() => setActiveId(item.id)}
                            />
                        );
                    })}
                </div>

                {/* Mobile masonry layout */}
                <div className="grid grid-cols-2 auto-rows-[180px] gap-3 sm:hidden mt-2">
                    {ACCORDION_ITEMS.map((item) => (
                        <MobileMasonryCard key={item.id} item={item} />
                    ))}
                </div>
            </div>
        </section>
    );
}

/* ------------------------------------------------------------------ */
/*  Mobile card (masonry)                                              */
/* ------------------------------------------------------------------ */

function MobileMasonryCard({ item }: { item: AccordionItem }) {
    const isTall = item.id === "food" || item.id === "fmcg";
    const isWide = item.id === "supermarket";

    return (
        <Link
            href={item.link}
            className={cn(
                "relative overflow-hidden rounded-xl group active:scale-[0.98] transition-transform duration-200 block",
                isTall && "row-span-2",
                isWide && "col-span-2"
            )}
        >
            <Image
                src={item.image}
                alt={item.title}
                fill
                className="object-cover transition-transform duration-700 group-hover:scale-110"
                sizes="(max-width: 640px) 100vw, 50vw"
                unoptimized={item.image.includes("wikimedia.org")}
                priority={item.id === "food" || item.id === "supermarket"}
            />
            <div
                className="absolute inset-0 flex flex-col justify-end p-4 text-white"
                style={{
                    background:
                        "linear-gradient(to bottom, rgba(4, 21, 43, 0) 0%, rgba(4, 21, 43, 0.4) 40%, rgba(4, 21, 43, 0.9) 100%)",
                }}
            >
                {isTall ? (
                    <>
                        <h2 className="text-[22px] sm:text-[24px] mb-1.5 font-bold leading-[1.15] font-sans tracking-tight whitespace-pre-line">
                            {item.displayTitle}
                        </h2>
                        <p className="text-[13px] text-white/80 mb-3.5 line-clamp-2 font-sans leading-snug">
                            {item.statSub}
                        </p>
                        <div
                            className="flex items-center text-[14px] font-medium text-indigo-900 bg-[#f8f9fa] w-fit px-4 py-1.5 rounded-full"
                        >
                            Join <ArrowRight className="w-4 h-4 ml-1.5" />
                        </div>
                    </>
                ) : isWide ? (
                    <>
                        <h2 className="text-[20px] mb-1.5 font-bold font-sans tracking-tight">
                            {item.title}
                        </h2>
                        <p className="text-[13px] text-white/80 mb-3.5 font-sans leading-snug">
                            {item.statHead} - {item.statSub}
                        </p>
                        <div
                            className="flex items-center text-[14px] font-medium text-indigo-900 bg-[#f8f9fa] px-4 py-1.5 rounded-full w-fit group-hover:bg-gray-100 transition-colors"
                        >
                            Explore Solutions <ArrowRight className="w-4 h-4 ml-1.5" />
                        </div>
                    </>
                ) : (
                    <>
                        <h2 className="text-[18px] mb-1 font-bold font-sans tracking-tight">
                            {item.title}
                        </h2>
                        <p className="text-[12px] text-white/80 font-sans leading-snug">
                            {item.statHead}
                        </p>
                    </>
                )}
            </div>
        </Link>
    );
}
